universe = vanilla
executable = project.sh
arguments = $(filename)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = compute_mean.py

output = logs/$(Cluster)_$(Process).out
error = logs/$(Cluster)_$(Process).err
log = logs/$(Cluster).log

container_image = docker://python:3.11

request_cpus = 1
request_memory = 6GB
request_disk = 4GB

queue filename from categories.txt
